services:
  valheim_server:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      - SERVER_NAME=Scrublheim2026
      - SERVER_WORLD=Scrublheim2026
      - SERVER_PASSWORD=Scrubs2026
      - ENABLE_PLUGINS=true
      - ENABLE_CROSSPLAY=false
      - Server_VISIBILITY=1
      - SERVER_SAVE_INTERVAL=1800
      - SERVER_BACKUPS=6
      - UPDATE_ALLOWED=false
      - LOCKED_BETA_BRANCH=default_public
    volumes:
      # Bind mount, to access the files directly on the host
      - ./valheim/server/:/root/valheim-server
      - ./valheim/persistentdata/:/root/.config/unity3d/IronGate/Valheim
    #This is required for ntsync to work inside Docker.
    #If ntsync support is not enabled in your Linux kernel, comment out this section, otherwise Docker Compose won't start.
#    devices:
#      - /dev/ntsync:/dev/ntsync
